name: Publish NuGet Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Pack
        run: dotnet pack src/Vicgital.Data.Sql/Vicgital.Data.Sql.csproj -c Release -o ./nupkg

      - name: Push to GitHub Packages
        run: dotnet nuget push "./nupkg/*.nupkg" --source "https://nuget.pkg.github.com/vicgital/index.json" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
